#!/bin/bash

if [[ -z "$(hostname -d)" ]]; then
    echo "Set up correct FQDN first!"
	logger -t "$(basename $0)" -s 'No valid FQDN found! Skipping setup...'
    exit 0
fi

echo "postfix postfix/mailname string $(hostname -f)" | debconf-set-selections
echo "postfix postfix/destinations string \$myhostname, $(hostname -s), localhost" | debconf-set-selections

echo $(hostname -f) > /etc/mailname

postconf -e "myhostname= $(hostname -f)"
postconf -e "mydestination= \$myhostname, $(hostname -s), localhost"

service postfix reload

# reconfigure postfix on boot
head -n -1 /etc/rc.local > /tmp/rc.local.tmp; grep -q '/usr/local/sbin/reconfigure-postfix' /tmp/rc.local.tmp || `echo -e "/usr/local/sbin/reconfigure-postfix\n\nexit 0" >> /tmp/rc.local.tmp; cat /tmp/rc.local.tmp > /etc/rc.local`

# mail to root
head -n -1 /etc/rc.local > /tmp/rc.local.tmp; grep -q 'ip a | tail -n +7 | s-nail -s "System (re-)started: \$(hostname)" root' /tmp/rc.local.tmp || `echo 'ip a | tail -n +7 | s-nail -s "System (re-)started: \$(hostname)" root' >> /tmp/rc.local.tmp; echo -e "\nexit 0" >> /tmp/rc.local.tmp; cat /tmp/rc.local.tmp > /etc/rc.local`
