#!/bin/bash

if [[ -z "$(which wbinfo)" || -z "$(wbinfo -t > /dev/null 2>&1 && echo ok)" ]]; then

    if [[ -z "$1" ]]; then
		logger -t "$(basename $0)" -s 'FQDN/hostname required! Skipping setup...'
        exit 1
    fi

    TMP_FQDN=$1
    hostnamectl set-hostname ${TMP_FQDN}

    if [[ -n "$(echo ${TMP_FQDN} | grep '\.')" ]]; then
        TMP_FQDN="${TMP_FQDN}\t${TMP_FQDN%%.*}"
    fi

    sed "s/^127.0.1.1.*/127.0.1.1\t${TMP_FQDN}/g" -i /etc/hosts

    # Machine ID
    rm -f /etc/machine-id
    dbus-uuidgen --ensure=/etc/machine-id

else
    echo "AD member detected. Exiting..."
fi
